### ISSUE TITLE
Lỗi ở bước loaddata demo

### ISSUE THREAD

**Issue by thanhnguyenhy** [LQDJudge/online-judge#108]
![image](https://github.com/LQDJudge/online-judge/assets/132742555/35a839ed-a4b1-474e-b01f-f5027d85f67f)
Cho mình hỏi sao đến bước này bị lỗi v ạ

**Comment by cuom1999** [comment]
Xin lỗi bạn, mình đã sửa ở đây https://github.com/LQDJudge/online-judge/commit/6c8926ec5660a7aa0ceda84ab7bd599fa1bc3d78.
