### ISSUE TITLE
Possible bug when showing full names on the contest leaderboard

### ISSUE THREAD

**Issue by jalsol** [LQDJudge/online-judge#13]
Leaderboard shows full names when the checkbox is **not** checked (and vice versa).

![](https://i.ibb.co/8bGjCL4/image.png)

Steps to reproduce:
- Open the leaderboard of a contest
- Check "Show full name"
- Move to another page (eg. the previous page, or a particular problem's ranking page) (*)
- Return to the leaderboard page

(*): If this another page requires *hard reloading* or some sorts, then the bug will **not** be produced.

**Comment by cuom1999** [comment]
Fixed with this [commit](https://github.com/LQDJudge/online-judge/commit/4cb2eaeaf187f4e9e317e99b229add180840e6dc). Thank you.
