### ISSUE TITLE
Lỗi DB khi đăng ký

### ISSUE THREAD

**Issue by emladevops** [LQDJudge/online-judge#40]
![image](https://user-images.githubusercontent.com/80335335/209455887-19eb662f-ce3b-4914-8126-04333c8e7d55.png)
Mình đang deploy một server riêng với source của LQDOJ, nhưng khi dùng tính năng đăng ký thì gặp lỗi này, bắt buộc phải ```SET FOREIGN_KEY_CHECKS = 1;``` mới hiện ra trang đăng ký thành công được (mặc dù vẫn nhận được mail activate)
Mong team LQDOJ xem xét và giúp đỡ mình ạ.

**Comment by cuom1999** [comment]
cái này là do thư viện newsletter (dùng để gửi email). Sau này mình sẽ bỏ thư viện này.

**Comment by emladevops** [comment]
Mình đã gửi request pull để fix tạm phần đăng ký.
