### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by emladevops** [LQDJudge/online-judge#45]
![image](https://user-images.githubusercontent.com/80335335/209558884-041f06c9-9ac8-4f92-b5f5-95d465e4d859.png)
Trong khi đang build LQDOJ trong WSL2 (Ubuntu 22.04) thì mình gặp lỗi trên. Mong team LQDOJ xử lí giúp mình ạ

**Comment by emladevops** [comment]
Sau khi populate timezone cho SQL, mình tiếp tục gặp lỗi này:
![image](https://user-images.githubusercontent.com/80335335/209559787-0960e3e1-e85e-43fd-b81d-06e965ab0ed0.png)

**Comment by emladevops** [comment]
```bash
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -D mysql -u root -p 
mysql -u root -p -e "flush tables;" mysql 
```

Docs cần bổ sung thêm phần này để fix lỗi ạ, Nếu pull request trước được duyệt, mình sẽ bổ sung thêm ý này vào README.md ạ.

![image](https://user-images.githubusercontent.com/80335335/209560395-cb318125-349c-4c15-93ae-8dcf6866a2bb.png)

**Comment by cuom1999** [comment]
Lỗi này mình cũng hay bị gần đây mà quên ghi lại. Cảm ơn bạn!
