### ISSUE TITLE
Judge live update

### ISSUE THREAD

**Issue by phuleethanh** [LQDJudge/online-judge#64]
Khi chấm bài site không liên tục cập nhật trạng thái chấm như bên LQDOJ, phải làm mới trang nó mới cập nhật.

Mình đã thử set EVENT_DAEMON_USE = False ở settings.py và local_settings.py nhưng vẫn chưa được. 

Xin hỏi phải set như thế nào để site liên tục cập nhật kết quả chấm. Xin cảm ơn

**Comment by phuleethanh** [comment]
Sau hồi tìm hiểu mình nhận thấy site và judge kết nối qua websocket để cập nhật liên tục khi chấm. Nên tệp cấu hình config.js, nginx.conf, và local_settings.py phải cấu hình socket giống nhau: cái 127.0.0.1 phải thay thành địa chỉ ip vps

**Comment by cuom1999** [comment]
127.0.0.1 chỉ đúng khi tất cả cùng chạy trên một server.
