### ISSUE TITLE
ScoreBoard của site

### ISSUE THREAD

**Issue by phuleethanh** [LQDJudge/online-judge#65]
Khi tổ chức kỳ thi có bài vẽ hình scratch, bài này sẽ chấm sau và cập nhật lên scoreboard sau khi test kết thúc.
Sau khi thi, mình chấm lại 5 bài nộp, tuy nhiên bảng xếp hạng chỉ cập nhật điểm mới của 2 bài. Dù restart site hay vps nó vẫn vậy.
Cho mình hỏi làm thế nào khắc phục vấn đề này?
Cảm ơn

**Comment by cuom1999** [comment]
vấn đề này hình như mình đã fix trong một commit gần đây
