### ISSUE TITLE
Thêm bài tập

### ISSUE THREAD

**Issue by phuleethanh** [LQDJudge/online-judge#66]
Hiện tại mình đang bị vướng hai thứ: 
  - Thêm bài tập dạng pdf là bị lỗi không thêm được mặc dù truy cập vps vẫn thấy thư mục bài tập và tệp pdf
  - Thêm bài là phải khởi động lại judge nó mới hiển thị là có máy chấm cho bài mới thêm 
Xin giúp mình cách khắc phục. Xin cảm ơn

**Comment by phuleethanh** [comment]
Mình mới khắc phục được việc không cần khởi động lại judge khi thêm bài tập bằng cách chạy inotifywait. Còn lỗi thêm bài tập dạng tệp pdf là chưa được :)

**Comment by emladevops** [comment]
> Mình mới khắc phục được việc không cần khởi động lại judge khi thêm bài tập bằng cách chạy inotifywait. Còn lỗi thêm bài tập dạng tệp pdf là chưa được :)

Bạn có dùng nginx không?

**Comment by cuom1999** [comment]
Nếu dùng nginx thì hình như cần thêm vài dòng kiểu này vào nginx.conf
```
location ~* .*/problems/.+\.pdf {
    # Serve problem pdf statements, should have the same path as PROBLEM_DATA_ROOT
    internal;
    root /;
}
```

**Comment by Khactrung1912** [comment]
Thầy có thể nói sơ qua về việc chạy inotifywait được không ạ?
Em có gặp tình trạng phải khởi động lại máy chấm mới chấm được và chạy inotifywait bằng lệnh inotifywait -m -r "dir" vẫn không được ạ
